# -*- coding: utf-8 -*-
"""JOGO DO ADIVINHA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wEHZim4uShR_V9W9jow95YuRzOSs4Kk7
"""

import random

help(random.randint)

numero= random.randint(1, 100)

contador = 0
while contador < 5:
  chute= input("Digite um número (1 a 100): ")
  chute= int(chute)
  diferenca = numero - chute
  if diferenca == 0:
    print("Você acertou")
    break
  elif diferenca > 0:
    if abs(diferenca) <= 10:
        print("Você errou, o valor é maior (está quente)")
    else:
        print("Você errou, o valor é maior (está frio)")
  else:
    if abs(diferenca) <= 10:
        print("Você errou, o valor é menor (está quente)")
    else:
        print("Você errou, o valor é menor (está frio)")
  contador = contador + 1
print("O número é: %s" % numero)

6